apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2   # 👈 base replicas (important for load balancing)
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: scoute/frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80

          # 🔥 IMPORTANT PART (for HPA)
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"